<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c40967c6-9941-4a9f-85d5-b337ef806fe2.ShoppingList.Api</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"/>
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Sinks.Async"/>
    <PackageReference Include="Swashbuckle.AspNetCore"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShoppingList.Client\ShoppingList.Client.csproj"/>
    <ProjectReference Include="..\ShoppingList.Shared\ShoppingList.Services.csproj"/>
  </ItemGroup>

</Project>
