<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="MudBlazor.ThemeManager" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShoppingList.Application\ShoppingList.Application.csproj"/>
    <ProjectReference Include="..\ShoppingList.Components\ShoppingList.Components.csproj"/>
    <ProjectReference Include="..\ShoppingList.Shared\ShoppingList.Services.csproj"/>
  </ItemGroup>

</Project>
 